[main]
backgroundPic = "https://michellelugomusic.github.io/MichelleLugoMusicResources/MusicMenusPic.jpeg"

[[entries]]
title = "Rings come and go"
desc = '''
I have made a musical, called Bathroom Breakup, of just three songs
about two girls on elementary school fighting over a boy. On the
first song, she enters the bathroom, and goes through her TikTok
only to see her ex making a new TikTok with another girl, which is
his new girlfriend. She starts singing of the shock.
'''
link = "https://michellelugomusic.github.io/MichelleLugoMusicResources/Rings-come-and-go.mp3"

[[entries]]
title = "You better duck"
desc = '''
In the second song, she enters the bathroom and they start fighting
about him.
'''
link = "https://michellelugomusic.github.io/MichelleLugoMusicResources/You-better-duck.mp3"

[[entries]]
title = "Sister for life"
desc = '''
In the third song, another girl enters the bathroom and tells them
to not fight over a boy, that there are more important things out
there than fight for a boy. And the story ends there.
'''
link = "https://michellelugomusic.github.io/MichelleLugoMusicResources/Sister-for-life-2.mp3"

[[extras]]
desc = '''
I have also made a second musical, in which it’s still in progress but you can follow along on our instagram:
'''
linkUrl = "https://www.instagram.com/willwilsonsavestheworldmusical/"
linkText = "https://www.instagram.com/willwilsonsavestheworldmusical/"
